
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.objects.NativeString.search;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Doğukan Yılmaz
 */
public class Main extends javax.swing.JFrame {
    DefaultTableModel urun_tablosu_model;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        urun_tablosu_model = (DefaultTableModel) urun_tablosu.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        urunname_input = new javax.swing.JTextField();
        urunbarkod_input = new javax.swing.JTextField();
        urunfiyat_input = new javax.swing.JTextField();
        urunadet_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        urunara_input = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mesaj_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ÜRÜN İSMİ :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("BARKOD :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("FİYAT :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("ADET :");

        urunname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunname_inputActionPerformed(evt);
            }
        });

        urunbarkod_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunbarkod_inputActionPerformed(evt);
            }
        });

        urunfiyat_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunfiyat_inputActionPerformed(evt);
            }
        });

        urunadet_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunadet_inputActionPerformed(evt);
            }
        });

        jButton1.setText("ÜRÜN EKLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ÜRÜN GÜNCELLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ÜRÜN SİL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ÜRÜNÜ SAT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÜRÜN ADI", "ÜRÜN BARKODU", "ÜRÜN FİYATI", "ÜRÜN ADEDİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);
        if (urun_tablosu.getColumnModel().getColumnCount() > 0) {
            urun_tablosu.getColumnModel().getColumn(0).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(1).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(2).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        urunara_input.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        urunara_input.setForeground(new java.awt.Color(204, 0, 0));
        urunara_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunara_inputActionPerformed(evt);
            }
        });
        urunara_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                urunara_inputKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("ARA :");

        mesaj_label.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        mesaj_label.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mesaj_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(urunara_input, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(urunfiyat_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(urunbarkod_input)
                            .addComponent(urunname_input)
                            .addComponent(urunadet_input, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(urunname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(urunbarkod_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(urunfiyat_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urunadet_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(mesaj_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(urunara_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urunname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunname_inputActionPerformed

    private void urunbarkod_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunbarkod_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunbarkod_inputActionPerformed

    private void urunfiyat_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunfiyat_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunfiyat_inputActionPerformed

    private void urunadet_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunadet_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunadet_inputActionPerformed
    
    
    boolean int_sorgula(String sayi) {
        try {               
            int urun_adet_int = Integer.parseInt(sayi); 
            return false;               
        } catch (Exception e) {
            return true;
        }
    }
    
    boolean double_sorgula(String sayi) {
        try {
            double urun_fiyat_double = Double.parseDouble(sayi);
            return false;
        } catch (Exception e) {
            return true;
        }
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mesaj_label.setText("");
        
        // ürün ekleme butonuna basıldığında
        
        String urun_adi = urunname_input.getText().toString();
        String urun_barkod = urunbarkod_input.getText().toString();
        String urun_fiyat = urunfiyat_input.getText().toString();
        String urun_adet = urunadet_input.getText().toString();
        
        //Hata arama 
        if (urun_adi.trim().equals("")) {
            mesaj_label.setText("Ürün adı boş girilemez!");
        } else if (urun_barkod.trim().equals("")) {
            mesaj_label.setText("Ürün barkodu boş girilemez!");
        } else if (urun_fiyat.trim().equals("")) {
            mesaj_label.setText("Ürün fiyatı boş girilemez!");
        } else if (urun_adet.trim().equals("")) {
            mesaj_label.setText("Ürün adedi boş girilemez!");
        } else if (int_sorgula(urun_adet)) {            
            mesaj_label.setText("Ürün adedi yazımı hatalı!");      
        } else if (double_sorgula(urun_fiyat)) {
            mesaj_label.setText("Ürün fiyatı yazımı hatalı!");
        } else {            
            Object[] eklenecek = {urun_adi,urun_barkod,urun_fiyat,urun_adet};            
            urun_tablosu_model.addRow(eklenecek);
            mesaj_label.setText("Ürün başarıyla eklendi!");
            urunname_input.setText("");
            urunbarkod_input.setText("");
            urunfiyat_input.setText("");
            urunadet_input.setText("");
        }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // ürün güncelleme işlemleri
        int row = urun_tablosu.getSelectedRow();
        if (row == -1) {
            if (urun_tablosu_model.getRowCount() == 0) {
                mesaj_label.setText("Tabloda güncellenecek veri yok!");
            } else {
               mesaj_label.setText("Lütfen güncellenecek ürünü seçiniz!");
            }
        } else {
            
              
        String urun_adi = urunname_input.getText().toString();
        String urun_barkod = urunbarkod_input.getText().toString();
        String urun_fiyat = urunfiyat_input.getText().toString();
        String urun_adet = urunadet_input.getText().toString();
        
        //Hata arama 
        if (urun_adi.trim().equals("")) {
            mesaj_label.setText("Ürün adı boş girilemez!");
        } else if (urun_barkod.trim().equals("")) {
            mesaj_label.setText("Ürün barkodu boş girilemez!");
        } else if (urun_fiyat.trim().equals("")) {
            mesaj_label.setText("Ürün fiyatı boş girilemez!");
        } else if (urun_adet.trim().equals("")) {
            mesaj_label.setText("Ürün adedi boş girilemez!");
        } else if (int_sorgula(urun_adet)) {            
            mesaj_label.setText("Ürün adedi yazımı hatalı!");      
        } else if (double_sorgula(urun_fiyat)) {
            mesaj_label.setText("Ürün fiyatı yazımı hatalı!");
        } else {           

            urun_tablosu_model.setValueAt(urun_adi,row, 0);
            urun_tablosu_model.setValueAt(urun_barkod,row, 1);
            urun_tablosu_model.setValueAt(urun_fiyat,row, 2);
            urun_tablosu_model.setValueAt(urun_adet,row, 3);            
            mesaj_label.setText("Ürün başarıyla güncellendi!");
            urunname_input.setText("");
            urunbarkod_input.setText("");
            urunfiyat_input.setText("");
            urunadet_input.setText("");
        } 
        
            
            
        }
        
        
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
        // tablodan bir ürüne tıkladığımda
        int row = urun_tablosu.getSelectedRow();
        urunname_input.setText(urun_tablosu_model.getValueAt(row, 0).toString());
        urunbarkod_input.setText(urun_tablosu_model.getValueAt(row, 1).toString());
        urunfiyat_input.setText(urun_tablosu_model.getValueAt(row, 2).toString());
        urunadet_input.setText(urun_tablosu_model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // ürün silme
        int row = urun_tablosu.getSelectedRow();
        if (row == -1) {
            if (urun_tablosu_model.getRowCount() == 0) {
                mesaj_label.setText("Tabloda silinecek veri yok!");
            } else {
               mesaj_label.setText("Lütfen silinecek ürünü seçiniz!");
            }
        } else {
            urun_tablosu_model.removeRow(row);
            mesaj_label.setText("Ürün başarıyla silindi");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // ürün satılmaya tıklandığında
         int row = urun_tablosu.getSelectedRow();
        if (row == -1) {
            if (urun_tablosu_model.getRowCount() == 0) {
                mesaj_label.setText("Tabloda satılacak veri yok!");
            } else {
               mesaj_label.setText("Lütfen satılacak ürünü seçiniz!");
            }
        } else {
            String urun_adedi = urun_tablosu_model.getValueAt(row, 3).toString();
            String urun_adi = urun_tablosu_model.getValueAt(row, 0).toString();
            int urun_adedi_int = Integer.parseInt(urun_adedi);
            if (urun_adedi_int > 0) {           
            urun_adedi_int--;
            if (urun_adedi_int == 0) {
                JOptionPane.showMessageDialog(this, urun_adi + " elimizde kalmadı!");
            }
            urun_tablosu_model.setValueAt(urun_adedi_int, row, 3);            
            mesaj_label.setText(urun_adi + " başarıyla satıldı");
            } else {
                mesaj_label.setText("Bu ürün stokta yok!");
            }
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void urunara_inputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urunara_inputKeyReleased
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(urun_tablosu_model);
        urun_tablosu.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(urunara_input.getText().toString()));
         
    }//GEN-LAST:event_urunara_inputKeyReleased

    private void urunara_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunara_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunara_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_label;
    private javax.swing.JTable urun_tablosu;
    private javax.swing.JTextField urunadet_input;
    private javax.swing.JTextField urunara_input;
    private javax.swing.JTextField urunbarkod_input;
    private javax.swing.JTextField urunfiyat_input;
    private javax.swing.JTextField urunname_input;
    // End of variables declaration//GEN-END:variables
}
